https://github.com/ernegreiros/BatalhaNaval/issues/52
ernegreiros/BatalhaNaval pull request #62
Opened 2020-11-08 14:37 UTC by PePires58

Favor verificar se falta algo, aparentemente tudo está ok.
Irei criar outra issue para os pontos q deixei faltando propositalmente.

@ernegreiros @ltakato

2020-11-08 19:34 UTC, ltakato approved these changes

2020-11-09 23:21 UTC, ernegreiros commented on Api/Battleship/BattleshipApi.Match/DAL/DispatcherMatch.cs
> +            stringBuilder.AppendLine("        SELECT TOP 1 1 FROM BattleField X WITH(NOLOCK)");
`SELECT TOP 1 1 FROM BattleField X WITH(NOLOCK)")`

**select 1 1** isso pode dar erro

2020-11-09 23:23 UTC, ernegreiros commented on Api/Battleship/BattleshipApi.MatchAttacks/DAL/DispatcherMatchAttacks.cs
> +            query.AppendLine($"SET @MATCH = { pMatchId }");
@TARGET INTERGER, arrumar o tipo

2020-11-09 23:26 UTC, ernegreiros requested changes
Checar comentarios

2020-11-10 23:56 UTC, PePires58 commented on Api/Battleship/BattleshipApi.Match/DAL/DispatcherMatch.cs
> +            stringBuilder.AppendLine("        SELECT TOP 1 1 FROM BattleField X WITH(NOLOCK)");
> `SELECT TOP 1 1 FROM BattleField X WITH(NOLOCK)")`
> 
> **select 1 1** isso pode dar erro

Na verdade não pode. Mesmo se não achar resultados, não retornará erro.
Pode criar uma tabela e realizar a query em questão.

2020-11-11 00:02 UTC, merged